version: '3.x'

services:
  tarantool1:
    build:
      context: database
    networks:
      - mynet

    container_name: my-tarantool-image

    ports:
      - "3302:3302"

  app:
    build: 
      context: .

    container_name: app

    depends_on:
      - tarantool1
    
    env_file:
      - .env

    ports:
      - "8001:8000"

networks:
  mynet:
    driver: bridge